name: Package Application with Pyinstaller

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:
  
  push:
    tags:
      - "v*.*.*"

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Package Application for Windows
  #     uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
  #     with:
  #       path: .
  #       spec: simpleFOCStudio.spec
  #       requirements: requirements.txt

  #   - name: Package Application for Linux
  #     uses: JackMcKew/pyinstaller-action-linux@python3.10
  #     with:
  #       path: .
  #       spec: simpleFOCStudio.spec
  #       requirements: requirements.txt

  #   - name: Rename files with details
  #     run: |
  #       mv dist/windows/simpleFOCStudio.exe dist/windows/simpleFOCStudio-windows-x86_64-${{ github.ref_name }}.exe
  #       mv dist/linux/simpleFOCStudio dist/linux/simpleFOCStudio-linux-x86_64-${{ github.ref_name }}
    

  #   - name: Release
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: |
  #         dist/windows/**
  #         dist/linux/**
  #         LICENSE

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'simpleFOCStudio.spec'
          requirements: 'requirements.txt'
          python_ver: '3.9'
          python_arch: 'x64'
          exe_path: './dist/windows'

      - name: Rename file with details
        run: mv dist/windows/simpleFOCStudio.exe dist/windows/simpleFOCStudio-windows-x86_64-${{ github.ref_name }}.exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/**

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'simpleFOCStudio.spec'
          requirements: 'requirements.txt'
          python_ver: '3.9'
          python_arch: 'x64'
          exe_path: './dist/linux'

      - name: Rename file with details
        run: mv dist/linux/simpleFOCStudio dist/linux/simpleFOCStudio-linux-x86_64-${{ github.ref_name }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/linux/**
