name: Package Application with Pyinstaller

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:
  
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
        spec: simpleFOCStudio.spec
        requirements: requirements.txt

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: .
        spec: simpleFOCStudio.spec
        requirements: requirements.txt

    - name: Rename files with details
      run: |
        mv dist/windows/simpleFOCStudio.exe dist/windows/simpleFOCStudio-windows-x86_64-${{ github.ref }}.exe
        mv dist/linux/simpleFOCStudio dist/linux/simpleFOCStudio-linux-x86_64-${{ github.ref }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/windows/*
          dist/linux/*
          LICENSE
