name: Package Application with Pyinstaller

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:
  
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: SimpleFOCStudio.spec
        requirements: requirements.txt
        

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/windows
          LICENSE
